
export const FETCH_CATEG_INIT = 'FETCH_CATEG_INIT';
export const FETCH_CATEG_START = 'FETCH_CATEG_START';
export const FETCH_CATEG_FAIL = 'FETCH_CATEG_FAIL';
export const FETCH_CATEG_RESET = 'FETCH_CATEG_RESET';
export const FETCH_CATEG = 'FETCH_CATEG';
export const FETCH_CATEG_SUCCESS = 'FETCH_CATEG_SUCCESS';
export const ADD_CATEG_INIT = 'ADD_CATEG_INIT';
export const ADD_CATEG = 'ADD_CATEG'; 
export const HIDE_MEDIA_BOX = 'HIDE_MEDIA_BOX';
export const SHOW_MEDIA_BOX = 'SHOW_MEDIA_BOX';
export const CHECK_LINK_INIT = 'CHECK_LINK_INIT';
export const CHECK_LINK = 'CHECK_LINK';
export const RESET_LINK = 'RESET_LINK';
export const ADD_SNAPSHOT = 'ADD_SNAPSHOT';
export const REMOVE_SNAPSHOT = 'REMOVE_SNAPSHOT';
export const SUBMIT_MEDIA = 'SUBMIT_MEDIA';
export const INPUT_DEFAULT_VALUE = 'INPUT_DEFAULT_VALUE';
export const REMOVE_MEDIA = 'REMOVE_MEDIA';
export const SUBMIT_FORM_INIT = 'SUBMIT_FORM_INIT';
export const SUBMIT_FORM_START = 'SUBMIT_FORM_START'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_FAIL = 'SUBMIT_FORM_FAIL'
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const IMAGE_CAPTURE = 'IMAGE_CAPTURE';




export const FETCH_POST_INIT = 'FETCH_POST_INIT';
export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_RESET = 'FETCH_POST_RESET';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';
export const FETCH_POST = 'FETCH_POST';